name: hiddenout

on:
  push:
    branches: [ main ]

# Create changelog and push  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current Time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
         format: YYYYMMDD-HH
         utcOffset: "+02:00"
      - name: Generate Result Directory
        env:
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
        run: mkdir test_results && echo $R_TIME > /home/runner/work/UITests/UITests/test_results/CHANGELOG.txt
      - name: Commit Results Directory
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPO_SECRET }}
        with:
          source_file: 'test_results'
          destination_repo: 'Fluctuationqt/hidden_results'
          destination_folder: 'nightly'
          user_email: ${{ secrets.REPO_MAIL }}
          user_name: ${{ secrets.REPO_UNAME }}
          commit_message: "Nighty results from: ${{ steps.current-time.outputs.readableTime }}"
      
