name: hiddenout

on:
  push:
    branches: [ main ]

# Create changelog and push 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Changelog
        run: echo "# Good things have arrived" > /home/runner/work/UITests/UITests/CHANGELOG.txt
      - name: Test Changelog
        run: cat /home/runner/work/UITests/UITests/CHANGELOG.txt
      - name: Release Changelog
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: /home/runner/work/UITests/UITests/CHANGELOG.txt
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: ${{ secrets.REPO_LOC }}
