name: hiddenout

on:
  push:
    branches: [ main ]

# Create changelog and push  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Changelog
        run: echo "# Good things have arrived" > /home/runner/work/UITests/UITests/CHANGELOG.txt
      - name: Test Changelog
        run: cat /home/runner/work/UITests/UITests/CHANGELOG.txt
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPO_SECRET }}
        with:
          source_file: 'CHANGELOG.txt'
          destination_repo: 'Fluctuationqt/hidden_results'
          destination_folder: 'test-results'
          user_email: ${{ secrets.REPO_MAIL }}
          user_name: ${{ secrets.REPO_UNAME }}
          commit_message: 'Results from current date' 
